pipeline {
    agent {
        label 'agent-1-label'
    }

    environment {
        project = 'expense'
        environment = 'dev'
    }

    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Please Choose the Right Action')
    }
  

    options {
        timeout(time: 40, unit: 'MINUTES')
        ansiColor('xtrem')
        disableConcurrentBuilds()        
    }

    stages {
        stage('terraform init') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-auth') {
                    sh """
                        cd 01-vpc
                        terraform init -reconfigure
                    """
                }
            }
        }

        stage('terraform plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-auth') {
                    sh """
                        cd 01-vpc
                        terraform plan -out=tfplan
                    """
                }
            }
        }

        stage('apply or destroy') {
            input(
                submitter: 'Naveen Rajoli',
                message: "Should we continue to ${params.ACTION}",
                ok: "yes, ${params.ACTION}"
            )
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-auth') {
                    sh """
                        if [ ${params.ACTION} == 'apply' ]
                        then
                            cd 01-vpc
                            terraform apply -auto-approve tfpaln
                        elif [ ${params.ACTION} == 'destroy' ]
                        then
                            cd 01-vpc
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }
    }


}